apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: test-deployment
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      group: test-pod
  template:
    metadata:
      labels:
        group: test-pod 
    spec:
      containers:
      - image: gcr.io/google_containers/pause-amd64:3.0
        name: {{.Name}}



